### ISSUE TITLE
wheel building fails

### ISSUE THREAD

**Issue by ajaeger** [openSUSE/spec-cleaner#167]
building wheels in OpenStack fails for spec-cleaner with:

   Running setup.py (path:/tmp/pip-build-TBK9mN/spec-cleaner/setup.py) egg_info for package spec-cleaner
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-TBK9mN/spec-cleaner/setup.py", line 7, in <module>
        from spec_cleaner import __version__
      File "spec_cleaner/__init__.py", line 12, in <module>
        from .rpmcleaner import RpmSpecCleaner
      File "spec_cleaner/rpmcleaner.py", line 28, in <module>
        from .rpmregexp import Regexp
      File "spec_cleaner/rpmregexp.py", line 6, in <module>
        class Regexp(object):
      File "spec_cleaner/rpmregexp.py", line 85, in Regexp
        re_configure = re.compile(r'(^|(.*\s)?)./configure($|(\s(.*)?))')
      File "/home/jenkins/workspace/wheel-build-centos-7-amd64-python2/build_env/lib64/python2.7/re.py", line 190, in compile
        return _compile(pattern, flags)
      File "/home/jenkins/workspace/wheel-build-centos-7-amd64-python2/build_env/lib64/python2.7/re.py", line 242, in _compile
        raise error, v # invalid expression
    sre_constants.error: nothing to repeat
Cleaning up...

Summary log file:
http://logs.openstack.org/periodic/wheel-build-centos-7-amd64-python2/2420b36/logs/failed.txt.gz

tar ball with several log files:
http://logs.openstack.org/periodic/wheel-build-centos-7-amd64-python2/2420b36/logs/build-logs.tar.bz2

**Comment by ajaeger** [comment]
building is done using
pip wheel --verbose -w /tmp/wheel spec-cleaner

and works on Fedora and openSUSE Leap 42.2.

Not sure yet why it fails on CentOS 7.

**Comment by ajaeger** [comment]
Duplicate of #165
