### ISSUE TITLE
version 0.9.6 broken

### ISSUE THREAD

**Issue by curantes** [openSUSE/spec-cleaner#191]
Hi,

I updated to version 0.9.6 of spec-cleaner on my Tumbleweed machine and now I just get the stack trace below when I try to run spec-cleaner. I hope you can resolv the issue.

Best Regards,
Matthias Eliasson

```python
Traceback (most recent call last):
  File "/usr/bin/spec-cleaner", line 11, in <module>
    load_entry_point('spec-cleaner==0.9.6', 'console_scripts', 'spec-cleaner')()
  File "/usr/lib/python3.6/site-packages/spec_cleaner/__init__.py", line 107, in main
    options = process_args(sys.argv[1:])
  File "/usr/lib/python3.6/site-packages/spec_cleaner/__init__.py", line 64, in process_args
    parser.print_help()
  File "/usr/lib64/python3.6/argparse.py", line 2362, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib64/python3.6/argparse.py", line 2346, in format_help
    return formatter.format_help()
  File "/usr/lib64/python3.6/argparse.py", line 282, in format_help
    help = self._root_section.format_help()
  File "/usr/lib64/python3.6/argparse.py", line 213, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib64/python3.6/argparse.py", line 213, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib64/python3.6/argparse.py", line 213, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib64/python3.6/argparse.py", line 213, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib64/python3.6/argparse.py", line 519, in _format_action
    help_text = self._expand_help(action)
  File "/usr/lib64/python3.6/argparse.py", line 606, in _expand_help
    return self._get_help_string(action) % params
ValueError: unsupported format character '{' (0x7b) at index 38
```

**Comment by sleep-walker** [comment]
fixed

**Comment by sleep-walker** [comment]
(and of course, thanks for the report :)
