### ISSUE TITLE
Does not show any available arguments

### ISSUE THREAD

**Issue by curantes** [openSUSE/spec-cleaner#238]
I use version 1.1.0 of spec-cleaner on Tumbleweed and when I try to get any argument info to console i get the following stack trace. If I run with known arguments it seems to work fine.

```
Traceback (most recent call last):
  File "/usr/bin/spec-cleaner", line 11, in <module>
    load_entry_point('spec-cleaner==1.1.0', 'console_scripts', 'spec-cleaner')()
  File "/usr/lib/python3.6/site-packages/spec_cleaner/__init__.py", line 97, in main
    options = process_args(sys.argv[1:])
  File "/usr/lib/python3.6/site-packages/spec_cleaner/__init__.py", line 69, in process_args
    parser.print_help()
  File "/usr/lib64/python3.6/argparse.py", line 2362, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib64/python3.6/argparse.py", line 2346, in format_help
    return formatter.format_help()
  File "/usr/lib64/python3.6/argparse.py", line 282, in format_help
    help = self._root_section.format_help()
  File "/usr/lib64/python3.6/argparse.py", line 213, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib64/python3.6/argparse.py", line 213, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib64/python3.6/argparse.py", line 213, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib64/python3.6/argparse.py", line 213, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib64/python3.6/argparse.py", line 519, in _format_action
    help_text = self._expand_help(action)
  File "/usr/lib64/python3.6/argparse.py", line 606, in _expand_help
    return self._get_help_string(action) % params
ValueError: unsupported format character '{' (0x7b) at index 28
```

**Comment by scarabeusiv** [comment]
Thanks for the report, there was missing % :)
