### ISSUE TITLE
Crashes on empty spec files in in-place mode

### ISSUE THREAD

**Issue by pjanouch** [openSUSE/spec-cleaner#91]
Detected by batch processing lots of files at once:
```
$ touch crash.spec
$ spec-cleaner -i crash.spec
```
causes:
```
Traceback (most recent call last):
  File "/usr/bin/spec-cleaner", line 9, in <module>
    load_entry_point('spec-cleaner==0.7.9', 'console_scripts', 'spec-cleaner')()
  File "/usr/lib/python3/dist-packages/spec_cleaner/__init__.py", line 96, in main
    cleaner.run()
  File "/usr/lib/python3/dist-packages/spec_cleaner/rpmcleaner.py", line 249, in run
    if line != '%changelog':
UnboundLocalError: local variable 'line' referenced before assignment
```

**Comment by scarabeusiv** [comment]
Nice catch, could you fix it? Should be simply if line and line !=..
